/**
 * GENERATED FILE — STUB.
 *
 * TODO(next unit): this file is generated by the Supabase CLI once the first
 * migration lands (schema ships with the feature that writes it — invariant #9):
 *
 *   supabase gen types typescript --linked > packages/db/src/database.types.ts
 *
 * Do not hand-edit beyond this stub. The shape below matches what the generator
 * emits for an empty schema so the client factories typecheck today.
 */
export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
