import { createRouter } from "@tanstack/react-router";
import { routeTree } from "./routeTree.gen";

// The router for the member SSR app (TanStack Start wiring — routeTree.gen.ts
// is generated by the Start vite plugin and committed so `tsc -b` typechecks
// before any build runs).
export function getRouter() {
  const router = createRouter({
    routeTree,
    scrollRestoration: true,
  });

  return router;
}

declare module "@tanstack/react-router" {
  interface Register {
    router: ReturnType<typeof getRouter>;
  }
}
